### PR TITLE
TypeScriptize

### LINKED ISSUE #4: Typescriptize
I'll convert egrid-sem.js to use by TypeScript.

### PR DESCRIPTION
**Pull request by armorik83**
Resolve #4, #5, #7.

- Introduce dev tools for TypeScript
- Convert egrid-sem to ts
- Create d.ts for egrid-sem

Thanks!

### CODE REVIEW

**Comment by armorik83** [comment]
Further resolve #6 (just a mistake push!)

**Comment by likr** [comment]
Thanks.

I have 2 questions.

* Running `dtsm install` seems to be required. Can I run dtsm using npm like `npm run dtsm` for consistency with `npm i` and `npm run bower` ?

* I couldn't build the project. Do I need additional settings or something ?
I run the following commands:
```
$ npm i
$ npm run bower
$ dtsm install
$ npm run
```
and I get the following output.

```
> egrid-sem@0.0.0 start /Users/likr/Downloads/interactive-sem
> grunt start && cd app && http-server

Running "clean:client" (clean) task
>> 0 paths cleaned.

Running "ts:clientMain" (ts) task
Compiling...
Using the custom compiler : ./node_modules/.bin/tsc
/Users/likr/Downloads/interactive-sem/app/src/scripts/injector/egrid.ts(2,10): error TS2304: Cannot find name 'egrid'.

>> 1 non-emit-preventing type warning
>> Error: tsc return code: 2
Warning: Task "ts:clientMain" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-02-02 23:37:13 UTC)
ts:clientMain  2.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 2.2s


npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/opt/local/bin/npm" "start"
npm ERR! node v0.10.29
npm ERR! npm  v2.1.2
npm ERR! code ELIFECYCLE
npm ERR! egrid-sem@0.0.0 start: `grunt start && cd app && http-server`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the egrid-sem@0.0.0 start script.
npm ERR! This is most likely a problem with the egrid-sem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt start && cd app && http-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls egrid-sem
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/likr/Downloads/interactive-sem/npm-debug.log
```

**Comment by armorik83** [comment]
Oops, sorry. I fixed.

**Comment by armorik83** [comment]
Building

```
npm i
npm run bower
npm run dtsm
npm start
```

**Comment by likr** [comment]
Thaks !

**Pull request merged**
